- name: Create Folder - "{{ item.dir }}"
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.15.232:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"

- name: Create Multi Branch Pipeline Jobs
  ansible.builtin.include_tasks: mbranch-sbranch-pipeline.yml
  loop: "{{ ci_pipeline_jobs }}"

- name: Create Single Branch Pipeline Jobs
  ansible.builtin.include_tasks: sbranch-sbranch-pipeline.yml
  loop: "{{ sbranch_pipeline_jobs }}"








