- name: Create Folder Config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml


- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml



