- name: Check if job exists or not
  community.general.jenkins_job_info:
    url: http://172.31.15.232:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}-1"
  register: out

- name: debug
  debug:
    msg: "{{out}}"

- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml


- name: Create Job - "{{item.dir}}/{{item.name}}"
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.15.232:8080
    user: admin
    password: "{{jenkins_password}}"


